package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/hkdb/flugo/internal/config"
)

var urlSchemeRe = regexp.MustCompile(`^[a-z][a-z0-9+.-]*$`)

// ApplyDeepLink registers the project's app.url_scheme across the platform
// files flutter owns after scaffold: the Android manifest intent-filter, the
// iOS and macOS Info.plist CFBundleURLTypes, and the Linux .desktop entry
// (re-rendered from the flugo template). All patches are idempotent — safe
// to run on every `flugo deeplink` invocation. The Dart-side wiring lives in
// the framework-owned main.dart (regenerated by `flugo update`/run/build);
// Windows HKCU registration happens at app startup via
// bridge.RegisterURLScheme.
func ApplyDeepLink(projectDir string, cfg *config.Config, cliVersion string) error {
	scheme := cfg.App.URLScheme
	if scheme == "" {
		return fmt.Errorf("app.url_scheme is not set in flugo.yaml")
	}
	if !urlSchemeRe.MatchString(scheme) {
		return fmt.Errorf("app.url_scheme %q is invalid (lowercase letters, digits, +, -, . only; must start with a letter)", scheme)
	}

	if err := patchAndroidManifestScheme(projectDir, scheme); err != nil {
		return err
	}
	for _, plist := range []string{
		filepath.Join(projectDir, "frontend", "ios", "Runner", "Info.plist"),
		filepath.Join(projectDir, "frontend", "macos", "Runner", "Info.plist"),
	} {
		if err := patchPlistURLScheme(plist, cfg.App.ID, scheme); err != nil {
			return err
		}
	}
	if err := renderDesktopFile(projectDir, cfg, cliVersion); err != nil {
		return err
	}
	return nil
}

// patchAndroidManifestScheme adds a VIEW/BROWSABLE intent-filter for the
// scheme to the main activity. No-op when already present.
func patchAndroidManifestScheme(projectDir, scheme string) error {
	path := filepath.Join(projectDir, "frontend", "android", "app", "src", "main", "AndroidManifest.xml")
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading AndroidManifest.xml: %w", err)
	}
	content := string(raw)
	marker := fmt.Sprintf(`android:scheme="%s"`, scheme)
	if strings.Contains(content, marker) {
		fmt.Println("  ✅ AndroidManifest.xml (already registered)")
		return nil
	}
	filter := fmt.Sprintf(`            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="%s"/>
            </intent-filter>
        </activity>`, scheme)
	if !strings.Contains(content, "</activity>") {
		return fmt.Errorf("AndroidManifest.xml has no </activity> to anchor the deep-link intent-filter")
	}
	content = strings.Replace(content, "</activity>", filter, 1)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing AndroidManifest.xml: %w", err)
	}
	fmt.Println("  ✅ AndroidManifest.xml")
	return nil
}

// patchPlistURLScheme adds CFBundleURLTypes to an Info.plist. No-op when the
// key already exists (any scheme set — flugo owns a single scheme).
func patchPlistURLScheme(path, appID, scheme string) error {
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		// Platform runner not generated (e.g. scaffolded without iOS) — skip.
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}
	content := string(raw)
	rel := filepath.Base(filepath.Dir(filepath.Dir(path))) + "/Runner/Info.plist"
	if strings.Contains(content, "CFBundleURLTypes") {
		fmt.Printf("  ✅ %s (already registered)\n", rel)
		return nil
	}
	block := fmt.Sprintf(`	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>%s</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>%s</string>
			</array>
		</dict>
	</array>
</dict>
</plist>`, appID, scheme)
	if !strings.Contains(content, "</dict>\n</plist>") {
		return fmt.Errorf("%s has an unexpected layout (no closing </dict></plist>)", rel)
	}
	content = strings.Replace(content, "</dict>\n</plist>", block, 1)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", rel, err)
	}
	fmt.Printf("  ✅ %s\n", rel)
	return nil
}

// renderDesktopFile re-renders assets/linux/<AppID>.desktop from the flugo
// template so the x-scheme-handler MimeType and Exec %u land in every
// packaging path (tarball, AppImage copies it, flatpak re-generates its own
// via `flugo flathub`).
func renderDesktopFile(projectDir string, cfg *config.Config, cliVersion string) error {
	tmpl, err := parseTemplates()
	if err != nil {
		return err
	}
	data := DataFromConfig(cfg, projectDir, cliVersion)
	path := filepath.Join(projectDir, "assets", "linux", cfg.App.ID+".desktop")
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating %s: %w", path, err)
	}
	defer f.Close()
	if err := tmpl.ExecuteTemplate(f, "desktop_file.tmpl", data); err != nil {
		return fmt.Errorf("rendering desktop file: %w", err)
	}
	fmt.Printf("  ✅ assets/linux/%s.desktop\n", cfg.App.ID)
	return nil
}
